# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.5
kind: Project
metadata:
  id: brigade-sdk-for-js
description: Brigade 2 SDK for JS built with Brigade 2!
spec:
  eventSubscriptions:
  - source: brigade.sh/github
    qualifiers:
      repo: brigadecore/brigade-sdk-for-js
    types:
    - check_run:rerequested
    - check_suite:requested
    - check_suite:rerequested
    - push
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/brigade-sdk-for-js.git
